# Generated by Django 3.2.16 on 2023-01-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['index']},
        ),
    ]
