# Generated by Django 3.2.16 on 2023-01-09 07:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['index'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Location name'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='index',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'longitude', 'latitude')},
        ),
    ]
